[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "dft"
author = "Gabriel Kabbe"
author-email = "gabriel.kabbe@chemie.uni-halle.de"
classifiers = ["License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"]

